apiVersion: v1
kind: Service
metadata:
  name: myinternalapp-loadbalancer
  namespace: dev
  labels:
    app: internalapp-deployment
    type: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 8090
      targetPort: 8082
  selector:
    app: myinternalapp
    